name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        sh .devcontainer/install-dependencies.sh
        /opt/devkitpro/portlibs/wii/bin/powerpc-eabi-cmake -B $GITHUB_WORKSPACE/build -G Ninja
        cmake --build $GITHUB_WORKSPACE/build --verbose

    - name: Prepare artifact
      run: |
        mkdir --parents artifact/MiisendU-Wii
        mv --verbose build/MiisendU-Wii.dol artifact/MiisendU-Wii/boot.dol
        cp --verbose meta/* artifact/MiisendU-Wii

    - uses: actions/upload-artifact@v4
      with:
        name: MiisendU-Wii
        path: artifact/
