name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v3

    - name: Build application
      run: |
        sh .devcontainer/install-dependencies.sh
        make build

    - name: Prepare artifact
      run: |
        mkdir --parents artifact/MiisendU-Wii
        mv --verbose MiisendU-Wii.dol artifact/MiisendU-Wii/boot.dol
        cp --verbose meta/* artifact/MiisendU-Wii

    - uses: actions/upload-artifact@v3
      with:
        name: MiisendU-Wii
        path: artifact/
